
export enum PluginStage {
    FETCHING = "FETCHING",
    FETCHED = "FETCHED",
    PARSING = "PARSING",
    PARSED = "PARSED",
    INSTANTIATING = "INSTANTIATING",
    INSTANTIATED = "INSTANTIATED",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    STOPPING = "STOPPING",
    STOPPED = "STOPPED"
}

export enum PluginDisableReason {
    REQUESTED = "REQUESTED",
    ERROR = "ERROR"
}
